### ISSUE TITLE
netty请求处理器v2的问题

### ISSUE THREAD

**Issue by ghost** [2YSP/rpc-spring-boot-starter#2]
为什么不直接在channelRead方法里面读取数据，反而搞了一个future。本来不就是异步的吗，这一步是不是多此一举了

**Comment by 2YSP** [comment]
SendHandlerV2的sendRequest（）方法是需要同步返回请求结果的，这里是利用Future阻塞等待服务端返回的数据，Netty本身是有线程池是异步的，但是一个SendHandlerV2对应一个TCP连接是一个线程，维度不一样。
